version: '2'
services:
  reverseproxy:
      build: ./docker/nginx
      ports:
          - "8080:80"
      restart: always
  apache:
    image: php:7.0-apache
    volumes:
      - ../:/var/www/html/
    external_links:
      - maria
  # maria: 
  #   image: mariadb
  #   environment:
  #       MYSQL_ROOT_PASSWORD: 'ROOT_PASSWORD'
  #       MYSQL_DATABASE: 'nyaa_db'
  #       MYSQL_USER: 'nyaa'
  #       MYSQL_PASSWORD: 'USER_PASSWORD'
  #   volumes:
  #     - "./docker/mariadb:/var/lib/mysql"
  #   ports:
  #     - "3306:3306"